Add exercism/maintainers-admin team as codeowner
exercism/java-analyzer pull request #25
Opened 2020-10-20 14:05 UTC by ErikSchierboom

The tooling is essential to the functioning of v3. To help ensure that any changes work well with the v3 website, the exercism/maintainers-admin team is added as a codeowner.

See https://github.com/exercism/exercism/issues/5400

2020-10-20 20:06 UTC, Smarticles101 requested changes
It appears something went wrong, I assume the intention was not to delete every file in the repo

2020-10-21 07:13 UTC, ErikSchierboom commented
@Smarticles101 Holy smokes, no that was _not_ the intention. I'll fix it!

2020-10-21 07:43 UTC, ErikSchierboom commented
@Smarticles101 It looks like there is an issue with a file path as I can't checkout the master branch on my Windows machine:

```
C:\code\java-analyzer [codeowners-maintainers]> git reset --hard origin/master
error: invalid path 'archive/hamming/170/src/main/java/\\src\\main\\java\\Hamming.java'
fatal: Could not reset index file to revision 'origin/master'.
```

2020-10-21 16:31 UTC, Smarticles101 approved these changes
Thanks Erik!

2020-10-21 16:31 UTC, merged