Create dependabot.yml
exercism/java-analyzer pull request #48
Opened 2021-11-09 15:14 UTC by FaisalAfroz

2021-11-10 10:28 UTC, mirkoperillo requested changes
Thank you for your contribution @FaisalAfroz.
Please move strings of configuration from `'` to `"`

2021-11-10 12:20 UTC, mirkoperillo approved these changes
good work, thank you

2023-09-19 07:53 UTC, sanderploegsma commented
@ErikSchierboom I found another one! Care to approve?

2023-09-19 08:03 UTC, ErikSchierboom approved these changes

2023-09-19 08:05 UTC, merged